version: '3.8'

services:
  app:
    build:
      context: ./docker/app
    ports:
      - "8080:8080"

  prometheus:
    build:
      context: ./docker/prometheus
    ports:
      - "9090:9090"

  grafana:
    build:
      context: ./docker/grafana
    ports:
      - "3000:3000"
